name: Cross Platform Tests
on:
  pull_request
jobs:
  cross-platform-tests:
    timeout-minutes: 30
    runs-on: macos-10.15
    steps:
      - name: Checkout cross platform test
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ANDROID_GITHUB_PAT }}  #medium-term solution, this needs to be an MParticle/non-personal PAT
          repository: mParticle/crossplatform-sdk-tests
      - name: Checkout internal
        uses: actions/checkout@v2
        with:
          path: .sdks/android

      - name: Start emulator
        run: cd .sdks/android; ./scripts/install-start-emulator.sh
      - name: Run Tests
        run: ./gradlew runAndroid
      - name: Archive Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Tests/build/reports/androidTests/connected/**
