name: Instrumented Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :android-core:cAT --stacktrace
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: android-core/build/reports/androidTests/connected/**